### ISSUE TITLE
JS Capstone Main Issue

### ISSUE THREAD

**Issue by jonathanmunamire** [jonathanmunamire/Movies-Api#16]
- Link to the [Project](https://github.com/users/jonathanmunamire/projects/3)
- In This Project, We are 2 People : @jonathanmunamire  and @Tamunokuro

**Comment by ha-manel** [comment]
# STATUS: INVALID 🔴 
Hi Team
This request is invalid because the link you provided for the kanban board is broken 😓  

Kindly fix the issue and submit the PR for review again 👍 
Best of luck!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by youmari** [comment]
# Project Approved :trophy: :tada: 🟢 

Hi @jonathanmunamire @Tamunokuro 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 


:heavy_check_mark: Details PR title and description.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
